"""empty message

Revision ID: b0a7c34d3074
Revises: 188c227e55bb
Create Date: 2016-01-30 23:19:43.261578

"""

# revision identifiers, used by Alembic.
revision = 'b0a7c34d3074'
down_revision = '188c227e55bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'info')
    op.drop_column('users', 'country')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
