"""empty message

Revision ID: fd5e1e405195
Revises: b0a7c34d3074
Create Date: 2016-01-31 15:41:39.751209

"""

# revision identifiers, used by Alembic.
revision = 'fd5e1e405195'
down_revision = 'b0a7c34d3074'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'users', 'posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('posts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('thread_posts')
    ### end Alembic commands ###
